import type { EpisodeQuizGameId } from './episodeQuizzes';

export const EPISODE_QUIZ_GAME_IDS = {
  "130": "colorful-balloons",
  "131": "golden-coins",
  "132": "treasure-hunter",
  "133": "colorful-balloons",
  "134": "golden-coins",
  "135": "treasure-hunter",
  "136": "colorful-balloons",
  "138": "golden-coins",
  "140": "treasure-hunter",
  "142": "colorful-balloons",
  "143": "golden-coins",
  "144": "treasure-hunter",
  "145": "colorful-balloons",
  "146": "golden-coins",
  "147": "treasure-hunter",
  "148": "colorful-balloons",
  "149": "golden-coins",
  "150": "treasure-hunter",
  "151": "colorful-balloons",
  "152": "golden-coins",
  "153": "treasure-hunter",
  "154": "colorful-balloons",
  "155": "golden-coins",
  "215": "treasure-hunter",
  "216": "colorful-balloons",
  "s2": "golden-coins",
  "s3": "treasure-hunter",
  "s4": "colorful-balloons",
  "s5": "golden-coins",
  "s6": "treasure-hunter",
  "s7": "colorful-balloons",
  "s8": "golden-coins",
  "s9": "treasure-hunter",
  "s10": "colorful-balloons",
  "s11": "golden-coins",
  "s12": "treasure-hunter",
  "s13": "colorful-balloons",
  "s14": "golden-coins",
  "s15": "treasure-hunter",
  "s16": "colorful-balloons",
  "s17": "golden-coins",
  "s18": "treasure-hunter",
  "s19": "colorful-balloons",
  "s20": "golden-coins",
  "s21": "treasure-hunter",
  "s22": "colorful-balloons",
  "s23": "golden-coins",
  "s24": "treasure-hunter",
  "s25": "colorful-balloons",
  "s26": "golden-coins",
} as const satisfies Record<string, EpisodeQuizGameId>;

export const EPISODE_QUIZ_IDS = Object.keys(EPISODE_QUIZ_GAME_IDS);
